
SET GLOBAL local_infile = 'ON';

LOAD DATA LOCAL INFILE './datasets/netflix_titles.csv' INTO TABLE Stream.netflix FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './datasets/hulu_titles.csv' INTO TABLE Stream.hulu FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './datasets/amazon_prime_titles.csv' INTO TABLE Stream.prime FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './datasets/disney_plus_titles.csv' INTO TABLE Stream.disney FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

